apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- patch/service.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml


