spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mlangeles/fleet-infra
    targetRevision: HEAD
  syncPolicy:
    automated: {}

argocd:
  namespace: argocd

nginxing:
  namespace: nginxing
  chart: ingress-nginx
  repoURL: https://kubernetes.github.io/ingress-nginx
  targetRevision: 4.9.1
  helm:
    parameters:
      - name: controller.service.type
        value: NodePort
      - name: controller.service.internal.nodePorts.http
        value: '31080'
      - name: controller.service.internal.nodePorts.https
        value: '31443'
    releaseName: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true