spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mlangeles/fleet-infra
    targetRevision: HEAD
  
  

apps:
  argocd:
    namespace: argocd
    type: kustomize

    syncPolicy:
      automated:
        prune: false
        selfHeal: false
      syncOptions:
      - CreateNamespace=true

  nginxing:
    namespace: nginxing
    type: helm
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.9.1

    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
    
