spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mlangeles/fleet-infra
    targetRevision: HEAD
  syncPolicy:
    automated: {}

argocd:
  namespace: argocd

nginxing:
  namespace: nginxing
  chart: ingress-nginx
  repoURL: https://kubernetes.github.io/ingress-nginx
  targetRevision: 4.9.1
  releaseName: nginx