spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mlangeles/fleet-infra
    targetRevision: HEAD
  syncPolicy:
    automated: {}

argocd:
  namespace: argocd