spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mlangeles/fleet-infra
    targetRevision: HEAD
  
  

apps:
  argocd:
    namespace: argocd
    type: kustomize
    syncPolicy:
      automated:
        prune: false
        selfHeal: false

  nginxing:
    namespace: nginxing
    type: helm
  
  harbor:
    namespace: harbor
    type: helm

  argoworkflow:
    namespace: argocd
    type: helm
    
  

